ExamenMvcNetCoreMonicaDelgado/Models/ErrorViewModel.cs
namespace ExamenMvcNetCoreMonicaDelgado.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamenMvcNetCoreMonicaDelgado/Models/Imagen.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamenMvcNetCoreMonicaDelgado.Models
{
    [Table("IMAGENESZAPASPRACTICA")]
    public class Imagen
    {
        [Key]
        [Column("IDIMAGEN")]
        public int IdImagen { get; set; }

        [Column("IDPRODUCTO")]
        public int IdProducto { get; set; }

        [Column("IMAGEN")]
        public string ImagenNombre { get; set; }
    }
}

ExamenMvcNetCoreMonicaDelgado/Models/Zapatilla.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamenMvcNetCoreMonicaDelgado.Models
{
    [Table("ZAPASPRACTICA")]
    public class Zapatilla
    {
        [Key]
        [Column("IDPRODUCTO")]
        public int IdProducto { get; set; }

        [Column("NOMBRE")]
        public string Nombre { get; set; }

        [Column("DESCRIPCION")]
        public string Descripcion { get; set; }

        [Column("PRECIO")]
        public int Precio { get; set; }
    }
}

ExamenMvcNetCoreMonicaDelgado/Models/ZapatillaImagen.cs
namespace ExamenMvcNetCoreMonicaDelgado.Models
{
    public class ZapatillaImagen
    {
        public Zapatilla Zapatilla { get; set; }
        public Imagen Imagen { get; set; }
    }
}

ExamenMvcNetCoreMonicaDelgado/Controllers/HomeController.cs
using System.Diagnostics;
using ExamenMvcNetCoreMonicaDelgado.Models;
using Microsoft.AspNetCore.Mvc;

namespace ExamenMvcNetCoreMonicaDelgado.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExamenMvcNetCoreMonicaDelgado/Controllers/ZapatillasController.cs
using ExamenMvcNetCoreMonicaDelgado.Models;
using ExamenMvcNetCoreMonicaDelgado.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ExamenMvcNetCoreMonicaDelgado.Controllers
{
    public class ZapatillasController : Controller
    {
        private RepositoryZapatillas repositoryZapatillas;

        public ZapatillasController(RepositoryZapatillas repo)
        {
            this.repositoryZapatillas = repo;
        }
        public async Task<IActionResult> Index()
        {
            List<Zapatilla> zapatillas = await this.repositoryZapatillas.GetZapatillasAsync();
            return View(zapatillas);
        }

        public async Task<IActionResult> Detalles(int idzapatilla)
        {
            Zapatilla zapatilla = await this.repositoryZapatillas.FindZapatillaByIdAsync(idzapatilla);
            return View(zapatilla);
        }

        public async Task<IActionResult> _ImagenesPartial(int? posicion, int idzapatilla)
        {
            if (posicion == null)
            {
                posicion = 1;
            }
            Zapatilla zapa = await this.repositoryZapatillas.FindZapatillaByIdAsync(idzapatilla);
            Imagen imagen = await this.repositoryZapatillas.GetImagenByPosAsync(idzapatilla, posicion.Value);
            

            int numRegistros = await this.repositoryZapatillas.GetNumeroImagenesByIdZapatillaAsync(idzapatilla);

            int siguiente = posicion.Value + 1;

            if (siguiente > numRegistros)
            {
                siguiente = numRegistros;
            }

            int anterior = posicion.Value - 1;
            if (anterior < 1)
            {
                anterior = 1;
            }

            ViewData["ULTIMO"] = numRegistros;
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            ViewData["POSICION"] = posicion;

            return PartialView("_ImagenesPartial",imagen);
        }
    }
}

ExamenMvcNetCoreMonicaDelgado/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExamenMvcNetCoreMonicaDelgado/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamenMvcNetCoreMonicaDelgado</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExamenMvcNetCoreMonicaDelgado.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExamenMvcNetCoreMonicaDelgado</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ExamenMvcNetCoreMonicaDelgado - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ExamenMvcNetCoreMonicaDelgado/Views/Zapatillas/Detalles.cshtml
@model Zapatilla
<ul class="list-group">
	<li class="list-group-item">@Model.Nombre</li>
	<li class="list-group-item">@Model.Precio</li>
	<li class="list-group-item">@Model.Descripcion</li>
</ul>
<div id="imagenes"></div>
@section Scripts{
	<script>
		function loadImagenProducto(posicion){
			$(function(){
				$("#imagenes").load("/Zapatillas/_ImagenesPartial?posicion=" + posicion + "&idzapatilla=" + @Model.IdProducto);
			});
		}
		loadImagenProducto(1);
	</script>
}

ExamenMvcNetCoreMonicaDelgado/Views/Zapatillas/Index.cshtml
@model IEnumerable<ExamenMvcNetCoreMonicaDelgado.Models.Zapatilla>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
          
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           
            <td>
                <a asp-controller="Zapatillas" asp-action="Detalles" asp-route-idzapatilla="@item.IdProducto">@item.Nombre</a>
            </td>
           
        </tr>
}
    </tbody>
</table>

ExamenMvcNetCoreMonicaDelgado/Views/Zapatillas/_ImagenesPartial.cshtml
@model Imagen

<button onclick="loadImagenProducto(1)">
	Primero
</button>
<button onclick="loadImagenProducto(@ViewData["ANTERIOR"])">
	Anterior
</button>
<button onclick="loadImagenProducto(@ViewData["SIGUIENTE"])">
	Siguiente
</button>
<button onclick="loadImagenProducto(@ViewData["ULTIMO"])">
	Ultimo
</button>


<div>
	<img style="width:150px;height:150px" src="@Model.ImagenNombre"/>
</div>